# Generated by Django 4.2.16 on 2025-06-26 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Ключ сессии",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы объект был активным",
                verbose_name="Активный",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_article",
            field=models.CharField(blank=True, max_length=50, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы объект был активным",
                verbose_name="Активный",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы объект был активным",
                verbose_name="Активный",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="orders_cart_user_id_7d3dad_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key"], name="orders_cart_session_953ed8_idx"
            ),
        ),
    ]
