# Generated by Django 4.2.16 on 2025-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_deliveryaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Контактный email"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Контактное лицо"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=13, verbose_name="Контактный телефон"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Внутренние заметки для администрации",
                verbose_name="Заметки",
            ),
        ),
    ]
