# Generated by Django 4.2.16 on 2025-06-29 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, чтобы объект был активным",
                        verbose_name="Активный",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
            ],
            options={
                "verbose_name": "Сообщение с формы обратной связи",
                "verbose_name_plural": "Сообщения с формы обратной связи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default='ОАО "Гомельский завод литейных изделий и нормалей"',
                        max_length=255,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "company_short_name",
                    models.CharField(
                        default="ГЗЛиН", max_length=50, verbose_name="Короткое название"
                    ),
                ),
                (
                    "company_description",
                    models.TextField(blank=True, verbose_name="Описание компании"),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+375 232 12-34-56",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@gomelzlin.by",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        default="246000, г. Гомель, ул. Промышленная, 15",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "working_hours",
                    models.TextField(
                        default="Пн-Пт: 8:00-17:00\nСб-Вс: выходной",
                        verbose_name="Режим работы",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=10,
                        verbose_name="Минимальная сумма заказа",
                    ),
                ),
                (
                    "cart_reservation_time",
                    models.PositiveIntegerField(
                        default=60,
                        verbose_name="Время резерва товара в корзине (минуты)",
                    ),
                ),
                (
                    "order_notification_email",
                    models.EmailField(
                        default="orders@gomelzlin.by",
                        max_length=254,
                        verbose_name="Email для уведомлений о заказах",
                    ),
                ),
                (
                    "admin_notification_email",
                    models.EmailField(
                        default="admin@gomelzlin.by",
                        max_length=254,
                        verbose_name="Email администратора",
                    ),
                ),
                (
                    "site_keywords",
                    models.TextField(
                        blank=True,
                        help_text="Через запятую",
                        verbose_name="Ключевые слова сайта",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Google Analytics ID"
                    ),
                ),
                (
                    "yandex_metrika_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Yandex Metrika ID"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, verbose_name="Режим технического обслуживания"
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="Сайт временно недоступен в связи с техническим обслуживанием.",
                        verbose_name="Сообщение о техническом обслуживании",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, чтобы объект был активным",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Отладка"),
                            ("INFO", "Информация"),
                            ("WARNING", "Предупреждение"),
                            ("ERROR", "Ошибка"),
                            ("CRITICAL", "Критическая ошибка"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Создание"),
                            ("UPDATE", "Обновление"),
                            ("DELETE", "Удаление"),
                            ("LOGIN", "Вход в систему"),
                            ("LOGOUT", "Выход из системы"),
                            ("ORDER_CREATED", "Создание заказа"),
                            ("ORDER_UPDATED", "Обновление заказа"),
                            ("PAYMENT_SUCCESS", "Успешная оплата"),
                            ("PAYMENT_FAILED", "Ошибка оплаты"),
                            ("PRODUCT_VIEWED", "Просмотр товара"),
                            ("CATEGORY_VIEWED", "Просмотр категории"),
                            ("SEARCH", "Поиск"),
                            ("EXPORT", "Экспорт данных"),
                            ("IMPORT", "Импорт данных"),
                            ("BACKUP", "Резервное копирование"),
                            ("SETTINGS_CHANGED", "Изменение настроек"),
                            ("LOW_STOCK", "Низкий остаток товара"),
                            ("SYSTEM_ERROR", "Системная ошибка"),
                        ],
                        max_length=50,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Системный лог",
                "verbose_name_plural": "Системные логи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["level", "created_at"],
                        name="core_system_level_8bfbf3_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="core_system_action__67ebc4_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_system_user_id_11cf62_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, чтобы объект был активным",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок для поисковых систем (до 60 символов)",
                        max_length=255,
                        verbose_name="SEO заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Описание для поисковых систем (до 160 символов)",
                        max_length=160,
                        verbose_name="SEO описание",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую",
                        max_length=255,
                        verbose_name="SEO ключевые слова",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автоматически генерируется из заголовка",
                        max_length=255,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "short_description",
                    tinymce.models.HTMLField(
                        help_text="Краткое описание для списка новостей",
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        help_text="Полный текст новости с форматированием",
                        verbose_name="Полное содержание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Основное изображение новости",
                        null=True,
                        upload_to="news/%Y/%m/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликовано"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Отображается на главной странице",
                        verbose_name="Рекомендуемая",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Оставьте пустым для автоматической установки при публикации",
                        null=True,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_active"],
                        name="core_news_status_aa2583_idx",
                    ),
                    models.Index(
                        fields=["published_at"], name="core_news_publish_a82f37_idx"
                    ),
                    models.Index(
                        fields=["is_featured", "status"],
                        name="core_news_is_feat_d50565_idx",
                    ),
                ],
            },
        ),
    ]
