# Generated by Django 4.2.16 on 2025-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы объект был активным",
                verbose_name="Активный",
            ),
        ),
        migrations.AlterField(
            model_name="systemlog",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы объект был активным",
                verbose_name="Активный",
            ),
        ),
    ]
