# Generated by Django 4.2.16 on 2025-06-29 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, чтобы объект был активным",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок для поисковых систем (до 60 символов)",
                        max_length=255,
                        verbose_name="SEO заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Описание для поисковых систем (до 160 символов)",
                        max_length=160,
                        verbose_name="SEO описание",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую",
                        max_length=255,
                        verbose_name="SEO ключевые слова",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        default='Открытое акционерное общество "Гомельский завод литейных изделий и нормалей"',
                        max_length=500,
                        verbose_name="Полное наименование",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default='ОАО "ГЗЛиН"',
                        max_length=100,
                        verbose_name="Краткое наименование",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="ГЗЛиН", max_length=100, verbose_name="Торговая марка"
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        default=1965, verbose_name="Год основания"
                    ),
                ),
                (
                    "history",
                    models.TextField(blank=True, verbose_name="История компании"),
                ),
                ("mission", models.TextField(blank=True, verbose_name="Миссия")),
                ("vision", models.TextField(blank=True, verbose_name="Видение")),
                (
                    "values",
                    models.TextField(
                        blank=True,
                        help_text="Каждая ценность с новой строки",
                        verbose_name="Ценности",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание деятельности"),
                ),
                (
                    "main_activities",
                    models.TextField(
                        blank=True,
                        help_text="Каждый вид деятельности с новой строки",
                        verbose_name="Основные виды деятельности",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+375 232 12-34-56",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="Факс"),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@gomelzlin.by",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "legal_address",
                    models.TextField(
                        default="246000, г. Гомель, ул. Промышленная, 15",
                        verbose_name="Юридический адрес",
                    ),
                ),
                (
                    "postal_address",
                    models.TextField(blank=True, verbose_name="Почтовый адрес"),
                ),
                (
                    "working_hours",
                    models.TextField(
                        default="Пн-Пт: 8:00-17:00\nСб-Вс: выходной",
                        verbose_name="Режим работы",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("vk_url", models.URLField(blank=True, verbose_name="ВКонтакте")),
                (
                    "unp",
                    models.CharField(
                        default="400123456",
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="УНП должен содержать 9 цифр", regex="^\\d{9}$"
                            )
                        ],
                        verbose_name="УНП",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Регистрационный номер"
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о компании",
                "verbose_name_plural": "Информация о компании",
            },
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, чтобы объект был активным",
                        verbose_name="Активный",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("director", "Директор"),
                            ("deputy_director", "Заместитель директора"),
                            ("chief", "Начальник"),
                            ("manager", "Менеджер"),
                            ("specialist", "Специалист"),
                        ],
                        default="specialist",
                        max_length=20,
                        verbose_name="Тип должности",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отдел/Подразделение"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company/leaders/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Руководитель",
                "verbose_name_plural": "Руководство",
                "ordering": ["sort_order", "position_type", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, чтобы объект был активным",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название организации"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Полное название"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Краткое описание партнерства или деятельности компании",
                        max_length=500,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("strategic", "Стратегический партнер"),
                            ("supplier", "Поставщик"),
                            ("customer", "Клиент"),
                            ("distributor", "Дистрибьютор"),
                            ("technology", "Технологический партнер"),
                        ],
                        default="strategic",
                        max_length=20,
                        verbose_name="Тип партнерства",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Рекомендуемый размер: 300x200 пикселей",
                        null=True,
                        upload_to="company/partners/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Беларусь", max_length=100, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "partnership_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала сотрудничества"
                    ),
                ),
                (
                    "cooperation_areas",
                    models.TextField(
                        blank=True,
                        help_text="Описание основных направлений сотрудничества",
                        verbose_name="Области сотрудничества",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Будет отображаться в приоритетном порядке",
                        verbose_name="Рекомендуемый партнер",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
                "ordering": ["-is_featured", "sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_public"],
                        name="company_par_is_acti_b359ab_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "sort_order"],
                        name="company_par_is_feat_81504b_idx",
                    ),
                ],
            },
        ),
    ]
