# Generated by Django 4.2.16 on 2025-06-25 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Оптимальная длина: 50-60 символов",
                        max_length=60,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Оптимальная длина: 150-160 символов",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        default='Открытое акционерное общество "Гомельский завод литейных изделий и нормалей"',
                        max_length=500,
                        verbose_name="Полное наименование",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default='ОАО "ГЗЛиН"',
                        max_length=100,
                        verbose_name="Краткое наименование",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="ГЗЛиН", max_length=100, verbose_name="Торговая марка"
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        default=1965, verbose_name="Год основания"
                    ),
                ),
                (
                    "history",
                    models.TextField(blank=True, verbose_name="История компании"),
                ),
                ("mission", models.TextField(blank=True, verbose_name="Миссия")),
                ("vision", models.TextField(blank=True, verbose_name="Видение")),
                (
                    "values",
                    models.TextField(
                        blank=True,
                        help_text="Каждая ценность с новой строки",
                        verbose_name="Ценности",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание деятельности"),
                ),
                (
                    "main_activities",
                    models.TextField(
                        blank=True,
                        help_text="Каждый вид деятельности с новой строки",
                        verbose_name="Основные виды деятельности",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+375 232 12-34-56",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="Факс"),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@gomelzlin.by",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "legal_address",
                    models.TextField(
                        default="246000, г. Гомель, ул. Промышленная, 15",
                        verbose_name="Юридический адрес",
                    ),
                ),
                (
                    "postal_address",
                    models.TextField(blank=True, verbose_name="Почтовый адрес"),
                ),
                (
                    "working_hours",
                    models.TextField(
                        default="Пн-Пт: 8:00-17:00\nСб-Вс: выходной",
                        verbose_name="Режим работы",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("vk_url", models.URLField(blank=True, verbose_name="ВКонтакте")),
                (
                    "unp",
                    models.CharField(
                        default="400123456",
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="УНП должен содержать 9 цифр", regex="^\\d{9}$"
                            )
                        ],
                        verbose_name="УНП",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Регистрационный номер"
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о компании",
                "verbose_name_plural": "Информация о компании",
            },
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("director", "Директор"),
                            ("deputy_director", "Заместитель директора"),
                            ("chief", "Начальник"),
                            ("manager", "Менеджер"),
                            ("specialist", "Специалист"),
                        ],
                        default="specialist",
                        max_length=20,
                        verbose_name="Тип должности",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отдел/Подразделение"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company/leaders/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Руководитель",
                "verbose_name_plural": "Руководство",
                "ordering": ["sort_order", "position_type", "last_name"],
            },
        ),
    ]
