# Generated by Django 4.2.16 on 2025-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, чтобы объект был активным",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название организации"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Полное название"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Краткое описание партнерства или деятельности компании",
                        max_length=500,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("strategic", "Стратегический партнер"),
                            ("supplier", "Поставщик"),
                            ("customer", "Клиент"),
                            ("distributor", "Дистрибьютор"),
                            ("technology", "Технологический партнер"),
                        ],
                        default="strategic",
                        max_length=20,
                        verbose_name="Тип партнерства",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Рекомендуемый размер: 300x200 пикселей",
                        null=True,
                        upload_to="company/partners/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Беларусь", max_length=100, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "partnership_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала сотрудничества"
                    ),
                ),
                (
                    "cooperation_areas",
                    models.TextField(
                        blank=True,
                        help_text="Описание основных направлений сотрудничества",
                        verbose_name="Области сотрудничества",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Будет отображаться в приоритетном порядке",
                        verbose_name="Рекомендуемый партнер",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
                "ordering": ["-is_featured", "sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_public"],
                        name="company_par_is_acti_b359ab_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "sort_order"],
                        name="company_par_is_feat_81504b_idx",
                    ),
                ],
            },
        ),
    ]
