# Generated by Django 4.2.16 on 2025-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы объект был активным",
                verbose_name="Активный",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Описание для поисковых систем (до 160 символов)",
                max_length=160,
                verbose_name="SEO описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова через запятую",
                max_length=255,
                verbose_name="SEO ключевые слова",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Заголовок для поисковых систем (до 60 символов)",
                max_length=255,
                verbose_name="SEO заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы объект был активным",
                verbose_name="Активный",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Описание для поисковых систем (до 160 символов)",
                max_length=160,
                verbose_name="SEO описание",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова через запятую",
                max_length=255,
                verbose_name="SEO ключевые слова",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Заголовок для поисковых систем (до 60 символов)",
                max_length=255,
                verbose_name="SEO заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы объект был активным",
                verbose_name="Активный",
            ),
        ),
    ]
