# Generated by Django 4.2.16 on 2025-06-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_fix_empty_slugs"),
        ("catalog", "0003_product_image_alter_product_min_stock_level_and_more"),
    ]

    operations = []
